# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docsclaw < Formula
  desc "Universal AI agent runtime with ConfigMap-driven personality"
  homepage "https://github.com/redhat-et/docsclaw"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/redhat-et/docsclaw/releases/download/v0.11.0/docsclaw_0.11.0_darwin_amd64.tar.gz"
      sha256 "1d9605d40b475ddc70204e1377663f9685577339388ce5ec9264b710448d76d4"

      define_method(:install) do
        bin.install "docsclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/redhat-et/docsclaw/releases/download/v0.11.0/docsclaw_0.11.0_darwin_arm64.tar.gz"
      sha256 "48ec12ca71113ffd60a3802835e5290b43e5c170d38038e3c51e1d197a2635ea"

      define_method(:install) do
        bin.install "docsclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/redhat-et/docsclaw/releases/download/v0.11.0/docsclaw_0.11.0_linux_amd64.tar.gz"
      sha256 "67f865de0d8c8f01cda8cf590a37f15fa74e598a3a88f3c5ce534aa8e11d37ff"
      define_method(:install) do
        bin.install "docsclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redhat-et/docsclaw/releases/download/v0.11.0/docsclaw_0.11.0_linux_arm64.tar.gz"
      sha256 "f4bb0046bd146815f4b662d12112c2dfe0f0ae2146e0bb669ed034ea469e46e8"
      define_method(:install) do
        bin.install "docsclaw"
      end
    end
  end
end
