# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docsclaw < Formula
  desc "Universal AI agent runtime with ConfigMap-driven personality"
  homepage "https://github.com/redhat-et/docsclaw"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/redhat-et/docsclaw/releases/download/v0.4.0/docsclaw_0.4.0_darwin_amd64.tar.gz"
      sha256 "6e1054727309f1ee4eb7918dae003b957440c733d0dbe13b9be102c029f7e4ed"

      define_method(:install) do
        bin.install "docsclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/redhat-et/docsclaw/releases/download/v0.4.0/docsclaw_0.4.0_darwin_arm64.tar.gz"
      sha256 "9543628818368760c0cc9dab6d815cb04dccec53a53395badb23a0d871e23c62"

      define_method(:install) do
        bin.install "docsclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/redhat-et/docsclaw/releases/download/v0.4.0/docsclaw_0.4.0_linux_amd64.tar.gz"
      sha256 "4f768469d43ac3e5b31a8450a686373366a6bdf8970d9d1e90beb2cc4fc1b6a8"
      define_method(:install) do
        bin.install "docsclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redhat-et/docsclaw/releases/download/v0.4.0/docsclaw_0.4.0_linux_arm64.tar.gz"
      sha256 "167d8a2932eaab8bbabde5c5a27bc0a42a9324132dd98287d203d22457c04cfa"
      define_method(:install) do
        bin.install "docsclaw"
      end
    end
  end
end
