# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillctl < Formula
  desc "Pack, push, pull, and inspect AI agent skills as OCI images"
  homepage "https://github.com/redhat-et/skillimage"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/redhat-et/skillimage/releases/download/v0.6.0/skillctl_0.6.0_darwin_amd64.tar.gz"
      sha256 "2afb7ceeb60cdeddfcd02ff8de87e0e4ad67347149dff948b482e80ca6172d9e"

      define_method(:install) do
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/redhat-et/skillimage/releases/download/v0.6.0/skillctl_0.6.0_darwin_arm64.tar.gz"
      sha256 "804d178f3963dd5d887f7db0f6c489fd885b69fd8ca7d662bf611fddc88b0633"

      define_method(:install) do
        bin.install "skillctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/redhat-et/skillimage/releases/download/v0.6.0/skillctl_0.6.0_linux_amd64.tar.gz"
      sha256 "b99ff0e54a703918e924afe7a9de6016a8babb32eeb62171f59648646f6b51d0"
      define_method(:install) do
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redhat-et/skillimage/releases/download/v0.6.0/skillctl_0.6.0_linux_arm64.tar.gz"
      sha256 "49f7c06539e03cc78ceecc94f7bc168c1a781d75f6607d0e1e32b5a5d26e84be"
      define_method(:install) do
        bin.install "skillctl"
      end
    end
  end
end
