# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillctl < Formula
  desc "Pack, push, pull, and inspect AI agent skills as OCI images"
  homepage "https://github.com/redhat-et/skillimage"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/redhat-et/skillimage/releases/download/v0.1.0/skillctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "102f8c40faaffbf1d7b40af492b7ad53ca0e95e9f25924a761b25cee41160649"

      define_method(:install) do
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/redhat-et/skillimage/releases/download/v0.1.0/skillctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "8322e28889280ef3297e5399ce1d080c8724872709a470277cbf47e3433eaced"

      define_method(:install) do
        bin.install "skillctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/redhat-et/skillimage/releases/download/v0.1.0/skillctl_0.1.0_linux_amd64.tar.gz"
      sha256 "a82d95a32bc4b5de3390c407ba09c4ffdf9353ea212404a7620a62e90702276e"
      define_method(:install) do
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redhat-et/skillimage/releases/download/v0.1.0/skillctl_0.1.0_linux_arm64.tar.gz"
      sha256 "86f8e03ad3b18b90c0f9567f732ebd5f07cd73c6340811235f14f445e4814d57"
      define_method(:install) do
        bin.install "skillctl"
      end
    end
  end
end
